package:
  name: shapes
  version: "0.1"

source:
  git_rev:
  git_url: https://github.com/codio-content/shapes-package

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - shapes

about:
  home: https://github.com/codio-content/shapes-package